version: "3.7"
services:
  server:
    build:
      context: ./ticket
      dockerfile: Dockerfile
      tags:
        - "ticket-project:1.0.0"
    container_name: service-ticket-project
    image: ticket-project:1.0.0
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8001"
      SERVICE: "ticket-api"
      APP_VERSION: "1.0.0"
      MONGODB_URI: "mongodb://test:test@mongo-ticket-project:27017"
      MONGODB_DB: ticket
      MONGODB_TIMEOUT: 10s
      AUTH_ACCESS_TOKEN_EXPIRE: 10m
      AUTH_REFRESH_TOKEN_EXPIRE: 1h
      AUTH_SECRET: "secret"
      AUTH_MODEL_PATH: "/app/asset/authmodel.conf"
      AUTH_POLICY_PATH: "/app/asset/authpolicy.json"
    ports:
      - 8001:8001
    networks:
      - project-network

  mongo:
    build:
      context: ./ticketdatabase
      dockerfile: Dockerfile
      tags:
        - "mongo-ticket-project:1.0.0"
    container_name: mongo-ticket-project
    image: mongo-ticket-project:1.0.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
    volumes:
      - "mongo_data:/data/db"
    networks:
      - project-network

  mongo-seed:
    build:
      context: ./ticketdatabase/seed
      dockerfile: Dockerfile
      args:
        - HOST=mongo-ticket-project
        - PORT=27017
        - DATABASE=ticket
        - DATABASE_URI=mongodb://test:test@mongo-ticket-project:27017
    container_name: mongo-seed
    links:
      - mongo
    networks:
      - project-network

volumes:
  mongo_data:
    name: project-database

networks:
  project-network:
    external: false
    name: project-network
